<%= "\n"*30 %>
<%= "# YOU ARE IN THE WRONG PLACE" %>
<%= "# YOU ARE IN THE WRONG PLACE use the ERB file" %>
<%= "# YOU ARE IN THE WRONG PLACE" %>

# Use an official Node.js runtime as the base image
FROM node:24-slim

# Set environment variables
ENV TZ=Etc/UTC
ENV NODE_ENV=production

# Create app directory
WORKDIR /fazabot

# Install system dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    ffmpeg \
    build-essential \
    libssl-dev \
    libffi-dev \
    && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y curl && \
    curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin/:$PATH"

# Install Python dependencies
RUN uv venv
ENV PATH="/fazabot/.venv/bin:$PATH"
RUN uv pip install --upgrade instaloader telethon python-dotenv "yt-dlp[default]"

# Copy package.json and yarn.lock
COPY ./containers/fazabot/src/src/package*.json ./containers/fazabot/src/src/yarn.lock ./

# Install Node.js dependencies
RUN yarn install

RUN rm -rf /var/lib/apt/lists/*

# Create necessary directories
RUN mkdir -p dist tmp

RUN chown -R <%= userid %>:<%= groupid %> /fazabot
