<%= "\n"*30 %>
<%= "# YOU ARE IN THE WRONG PLACE" %>
<%= "# YOU ARE IN THE WRONG PLACE use the ERB file" %>
<%= "# YOU ARE IN THE WRONG PLACE" %>

FROM docker.io/library/ubuntu:latest

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

# Install Node.js 18
RUN mkdir -p /etc/apt/keyrings
RUN apt-get update && apt-get install -y curl gnupg
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list

RUN apt-get update && \
	apt-get install -y build-essential software-properties-common \
	nodejs=18.* python3 python3-dev python3-pip ffmpeg wget vim pkg-config \
	libpixman-1-dev libcairo2-dev libpango1.0-dev libjpeg8-dev libgif-dev

COPY ./containers/1chat/src/src/animalicons/fonts/ /usr/share/fonts/truetype/
RUN fc-cache -fv

RUN npm i -g yarn

RUN mkdir -p /home/app/1chat/dist /home/app/1chat/.cache/yarn
COPY ./containers/1chat/src/package.json /home/app/1chat/
COPY ./containers/1chat/src/yarn.lock /home/app/1chat/
COPY ./containers/1chat/src/tsconfig.json /home/app/1chat/tsconfig.json
WORKDIR /home/app/1chat
RUN yarn

RUN chown -R <%= userid %>:<%= groupid %> /home/app/1chat
