<%= "\n"*30 %>
<%= "# YOU ARE IN THE WRONG PLACE" %>
<%= "# YOU ARE IN THE WRONG PLACE use the ERB file" %>
<%= "# YOU ARE IN THE WRONG PLACE" %>

FROM docker.io/library/ubuntu:latest

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

# get install script and pass it to execute:
RUN apt-get update && apt-get install -y curl
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
# and install node
RUN apt-get update && apt-get install -y build-essential \
    software-properties-common vim python3 python3-dev nodejs rsync

RUN corepack enable && corepack prepare pnpm@latest --activate
RUN mkdir -p /livla/build/dumps
COPY ./containers/livla/src/src/package.json ./containers/livla/src/src/pnpm-lock.yaml /livla/
COPY ./containers/livla/src/src/tsconfig.json /livla/
WORKDIR /livla
RUN pnpm install --frozen-lockfile
RUN chown -R <%= userid %>:<%= groupid %> /livla
